### ISSUE TITLE
Bot crashes after pressing the start button

### ISSUE THREAD

**Issue by mcanducci** [social-manager-tools/socialmanagertools-twbot#15]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.2.5
- **Node Version:** v10.15.3 (Bot require >= 7.6)
- **Operating System:** MacOS 10.14
- **Browser:** Google Chrome 64

### Expected Behavior
I expect that bot starts after pressing on START

### Actual Behavior
After filling the form and pressing on START the bot freezes, the mouse pointer became an hand and the only thing I have to do is close the app.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... run SMT and select Twitter Bot
2. ... fill the form
3. ... press START

### config.js (remember to remove password)
```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
Hi @mcanducci 
What is number of like/rt you set? Try more than 100.

**Comment by mcanducci** [comment]
It works! 
Thanks!
